### ISSUE TITLE
An attribute list can not appear here

### ISSUE THREAD

**Issue by maidamai0** [jarro2783/cxxopts#354] opened 2022-07-18 02:09 UTC
clang complains about the `An attribute list can not appear here`:
https://github.com/jarro2783/cxxopts/blob/e976f964c3ee6a4f6faa836ecb38f3ff8b043114/include/cxxopts.hpp#L1252

move the `CXXOPTS_NODISCARD` before `inline` can make clang quiet

**Comment by jarro2783** [comment] 2022-07-18 11:01
Duplicate of #353

**Closed by jarro2783** 2022-07-18 11:01 UTC
