### ISSUE TITLE
When using Chinese Debug mode in Visual Studio, the assertion fails in std::isblank

### ISSUE THREAD

**Issue by 66maer** [jarro2783/cxxopts#364] opened 2022-09-01 08:37 UTC
![image](https://user-images.githubusercontent.com/10154859/187870478-92f84c5e-2f4d-47cb-90c9-d11bf57df638.png)

![image](https://user-images.githubusercontent.com/10154859/187870760-a2e6b0d3-44ae-4e43-8fba-d912c9eba9c7.png)

```c++
extern "C" int __cdecl _chvalidator(int const c, int const mask)
{
    _ASSERTE(c >= -1 && c <= 255);
    return _chvalidator_l(nullptr, c, mask);
}
```

**Comment by jarro2783** [comment] 2022-09-07 21:33
Fixed by #365

**Closed by jarro2783** 2022-09-07 21:33 UTC

**Comment by hillmich** [comment] 2022-09-09 08:05
This PR breaks the build on our CI on MacOS (see [corresponding run](https://github.com/cda-tum/ddsim/runs/8264664336?check_suite_focus=true) on cda-tum/ddsim#123, error also stated below). It seems to me this is not caused by our code. Would you be wiling to have a look?

```
...
In file included from /Users/runner/work/ddsim/ddsim/apps/simple.cpp:10:
/Users/runner/work/ddsim/ddsim/extern/cxxopts/include/cxxopts.hpp:2093:33: error: too many arguments to function call, expected single argument '_c', have 2 arguments
    if (std::isblank(*previous, std::locale::classic()))
        ~~~~~~~~~~~~            ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/_ctype.h:224:1: note: 'isblank' declared here
isblank(int _c)
^
In file included from /Users/runner/work/ddsim/ddsim/apps/simple.cpp:10:
/Users/runner/work/ddsim/ddsim/extern/cxxopts/include/cxxopts.hpp:2098:33: error: too many arguments to function call, expected single argument '_c', have 2 arguments
    if (!std::isblank(*current, std::locale::classic()))
         ~~~~~~~~~~~~           ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/_ctype.h:224:1: note: 'isblank' declared here
isblank(int _c)
^
2 errors generated.
```

**Comment by jarro2783** [comment] 2022-09-10 00:57
According to https://en.cppreference.com/w/cpp/locale/isblank that function is supported by C++11. Is this a recent compiler? It might need an exception for your compiler if it doesn't support that function signature.

**Comment by hillmich** [comment] 2022-09-10 07:53
The mentioned overload of `isblank` is from a header that's not included in `cxxopts.hpp`. I hope you don't mind that I created #368 :)
