### ISSUE TITLE
Garbled font when giving unknown option

### ISSUE THREAD

**Issue by patrikhuber** [jarro2783/cxxopts#64] opened 2017-08-12 22:16 UTC
Hi,

I'm running the `example` app from this repo. 
When I give it an unkown option, for example run `example.exe -e`, I get all garbled output:

```
error parsing options: Option ├óÔé¼╦£e├óÔé¼Ôäó does not exist
Press any key to continue . . .
```

This is on VS 2017 Preview (15.3.0 Preview 7.1), x64. Happens in Debug and Release build. I didn't change any of the default options of the `example` app, so e.g. `CXXOPTS_USE_UNICODE` is not defined.

Running the tests:

```
===============================================================================
All tests passed (53 assertions in 13 test cases)

Press any key to continue . . .
```

**Comment by patrikhuber** [comment] 2017-08-12 22:55
The problem seem to be the quotes [here](https://github.com/jarro2783/cxxopts/blob/master/include/cxxopts.hpp#L340):

`: OptionParseException(u8"Option ‘" + option + u8"’ does not exist")`

Did you mean to use the "normal" quotes (`'`) instead? If I replace your quotes with `'`, it works fine.

**Comment by jarro2783** [comment] 2017-08-13 21:59
This is a duplicate of #34.

**Closed by jarro2783** 2017-08-13 21:59 UTC

**Comment by patrikhuber** [comment] 2017-08-13 22:44
@jarro2783 Thanks for the link. Oh wow. What a mess this is. It seems like all that is really not worth just keeping fancy quotes. Anyway I'll have a look at the steps mentioned there :-)

**Comment by jarro2783** [comment] 2017-08-13 22:58
Yeah it's probably not worth keeping the fancy quotes. When I get to it I'll provide a way to `#ifdef` them out.
