### ISSUE TITLE
Compiler error when calling parse function with mutable argv

### ISSUE THREAD

**Issue by pluehne** [jarro2783/cxxopts#110] opened 2018-04-09 17:46 UTC
Since #99 was merged (I’m using `cxxopts` 2.1.0 now), simple usage examples like the following fail:

```cpp
#include <cxxopts.hpp>

int main(int argc, char *argv[])
{
	cxxopts::Options options("test");
	options.parse(argc, argv);

	return 0;
}
```

with the error message (`g++` 7.3.1):

```cpp
test.cpp: In function ‘int main(int, char**)’:
test.cpp:6:26: error: invalid conversion from ‘char**’ to ‘const char**’ [-fpermissive]
  options.parse(argc, argv);
                          ^
In file included from test.cpp:1:0:
cxxopts.hpp:1642:1: note:   initializing argument 2 of ‘cxxopts::ParseResult cxxopts::Options::parse(int&, const char**&)’
 Options::parse(int& argc, const char**& argv)
 ^~~~~~~
test.cpp:6:26: error: cannot bind rvalue ‘(const char**)argv’ to ‘const char**&’
  options.parse(argc, argv);
```

The reason is that `char *argv[]` (or `char **argv`) cannot be implicitly converted to `const char **`, which is used in all `parse` function signatures.

I know that #99 added the `const` qualifier for a reason. I like the idea suggested by @vladimirgamalyan in #91 to turn `const char **&argv` in the `parse` function signatures into `const char * const *&argv`. However, I think that’s not possible right now, because `argv` is modified by `cxxopts` such as in:https://github.com/jarro2783/cxxopts/blob/0fe1dc892bcbef48b3911510209c7033f31ce05e/include/cxxopts.hpp#L1681

Still, I think that this should be addressed, because `int main(int argc, char *argv[])` is a standard main function signature, which should be supported by `cxxopts`. If that’s not feasible, it would be good to mention this in the readme at least :slightly_smiling_face:.

**Comment by SkullTech** [comment] 2018-04-09 19:32
I'm having the same issue. Resolving it would be a priority as all the basic code in the README or the `example.cpp` file do not work out of the box right now.

**Comment by pluehne** [comment] 2018-04-09 20:09
@SkullTech: Actually, the example compiles, because its main function signature was adjusted:https://github.com/jarro2783/cxxopts/blob/0f819a5cabb611ada4c41a5208c6bf1178f804be/src/example.cpp#L29 But I agree that basic code like above should work out of the box, especially since there is no mention in the readme.

**Comment by SkullTech** [comment] 2018-04-09 20:19
@pluehne There should be some way to make it work with the standard signature of the `main` function, since the same arguments are sometimes expected by other libraries or frameworks, such as [`QApplication`](http://doc.qt.io/qt-5/qapplication.html#QApplication) of the `QT` framework.

I need to make this work urgently, so can anyone help me out how should I proceed. I guess there is a way I can convert a `const` into a non-`const`?

**Comment by jarro2783** [comment] 2018-04-09 22:01
Sorry about that. I didn't look closely enough at that PR and it looked safe with the tests passing. I'll come up with a fix.

**Comment by pluehne** [comment] 2018-04-09 22:05
@jarro2783: No worries! I stumbled upon the issue and just wanted to let you know :slightly_smiling_face:.

**Comment by jarro2783** [comment] 2018-04-10 22:32
I've reverted the offending commit in cc4914f0.

**Closed by jarro2783** 2018-04-10 22:32 UTC

**Comment by pluehne** [comment] 2018-04-11 09:30
@jarro2783: Thanks a lot :+1:!

**Comment by ruslo** [comment] 2018-06-06 01:20
> I've reverted the offending commit in cc4914f.

@jarro2783 Can you please make a release with this change?

**Comment by jarro2783** [comment] 2018-06-12 22:06
Sure. I'll do another release soon.

**Comment by pluehne** [comment] 2018-06-12 22:06
@jarro2783: Thanks!

**Comment by Marandil** [comment] 2018-07-12 15:33
I don't think this was the right direction, as now it fails with main signature of `int main(int argc, const char *argv[])`.
I guess the real question should be, why is `argv` passed as a reference instead of value, since it doesn't seem to be modified directly (i.e. there is no `argv = ...`).

**Comment by MikeGitb** [comment] 2018-08-03 08:57
@Marandil: Isn't that main signature illegal anyway? And as @pluehne mentioned: cxxopts actually does modify `argv`.

**Comment by MikeGitb** [comment] 2018-08-03 11:01
@Marandil: You are probably right, that it is not illegal. The standard says

> An implementation shall allow both
(2.1) — a function of () returning int and
(2.2) — a function of (int, pointer to pointer to char) returning int

that doesn't forbid adding another overload 

> (int, pointer to pointer to **const** char)` returning int

FYI:
> IIRC, you are free to add as many const qualifiers as you wish in function definition

You can add top-level const qualifiers (`main(int argc, char** const argv)`  not somewhere further down the chain because that would change the type .

> BTW: my question about passing argv as reference is still valid. I see why const char* const argv[] cannot be used, but I don't see why the less-restrictive const char* argv[] cannot.

The problem is  that you cannot implicitly convert the standard signature `char** argv` to `const char** argv`, you need to use `const_cast` : https://godbolt.org/g/x9urEC

**Comment by Marandil** [comment] 2018-08-03 11:26
@MikeGitb OK, I dug around for a bit and I think I get the idea why you cannot freely swap those things around in this case - [this](https://stackoverflow.com/a/78218/2267742) SO answer has a pretty good example.
Apparently, ensuring const correctness, you can cast `char**` to `const char* const*` (https://godbolt.org/g/AMJ1uF), but I understand why this is tricky in case of this lib (the pointers are being swapped around).
Still trying to push for removing the reference though :).

**Comment by MikeGitb** [comment] 2018-08-03 12:25
@Marandil: 
Removal of the reference is probably possible (Ihaven't checked), but afaik doesn't really gain you a lot. 

Imho the simplest solution would be to offer two overloads (one for `const char**` and one for `char**`) and internally do the `const_cast` from `char**` to `const char**`

**Comment by jarro2783** [comment] 2018-08-05 22:40
I think @Marandil has found the right reason for this in that SO answer.

The best solution here would be to have a function that takes a `const` `argv`. The only problem is that I am modifying `argv` to leave unrecognised or positional options behind, so I will have to provide a separate interface for accessing those.
